### ISSUE TITLE
No more sound output on Odroid N2+ after updating to Supervisor 2023.11.0

### ISSUE THREAD

**Issue by GoSpursGoNL** [home-assistant/plugin-audio#157]
### Describe the issue you are experiencing

Earlier this week my system updated to HA Supervisor 2023.11.0
Immediate the sound output of the board's 3.5mm output (via VLC addon as always) stopped working.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Update to Supervisor 2023.11.0
2. Play some sound on local audio output via VLC addon

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.vlc_telnet
Source: components/vlc_telnet/media_player.py:62
Integration: VLC media player via Telnet (documentation, issues)
First occurred: 8 november 2023 om 20:31:21 (2 occurrences)
Last logged: 10:15:38
Connection error: Failed to read: 0 bytes read on a total of undefined expected bytes. Partial bytes read: b''
```

## System Information

version | core-2023.11.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 5.15.90
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1328
Downloaded Repositories | 7

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 19

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.0
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 113.9 GB
disk_used | 91.6 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.2), Duck DNS (1.15.0), Home Assistant Google Drive Backup (0.111.1), NGINX Home Assistant SSL proxy (3.5.0), Node-RED (15.1.0), Plex Media Server (3.3.2), Advanced SSH & Web Terminal (15.1.0), WireGuard (0.9.0), AdGuard Home (4.8.17), VLC (0.2.0), Zigbee2MQTT (1.33.2-1), Mosquitto broker (6.3.1), chrony (2.6.2), ESPHome (2023.10.6), File editor (5.6.0), HomePod Connect (28.8-ls118), Whisper (1.0.0), Piper (1.4.0), Music Assistant BETA (2.0.0b74), openWakeWord (1.8.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 2
views | 10
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 8 november 2023 om 18:04
-- | --
current_recorder_run | 8 november 2023 om 19:05
estimated_db_size | 104.43 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Supervisor diagnostics

[config_entry-hassio-f9c2513652a4f6291037d6fa4f7c58d8.json.txt](https://github.com/home-assistant/supervisor/files/13317687/config_entry-hassio-f9c2513652a4f6291037d6fa4f7c58d8.json.txt)

**Comment by therealhammer** [comment]
Having the same problem here. Weirdly enough pulse is trying to recognize two audio devices that are both not found.

Audio log:
`[...] 
W: [pulseaudio] module-udev-detect.c: Failed to open /proc/asound/card1: No such file or directory
W: [pulseaudio] module-udev-detect.c: Failed to open /proc/asound/card0: No such file or directory
E: [pulseaudio] bluez5-util.c: GetManagedObjects() failed: org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer: unit failed. `

**Comment by agners** [comment]
The fix is currently on the beta channel. You can update the Audio plug-in specifically using:

```
ha audio update --version 2023.12.0
```

You might need to restart the VLC add-on after that.

**Comment by spudje** [comment]
Cool it's fixed. Is this part of 2023.12.1 version of supervisor?

**Comment by agners** [comment]
The audio plug-in is updated separately. The 2023.12.0 version of the audio plug-in is on the stable channel since a couple of days.

**Comment by spudje** [comment]
It's not fixed for me. I'm on 2023.12.0. Haven't rebooted the Odroid yet though and my OS is also still on 11.2, so maybe those are reasons.

**Comment by agners** [comment]
OS 11.2 should not matter, but reboot might be the problem. If the problem still persists after reboot, double check the audio plug-in version (using `ha audio info` from the terminal).

**Comment by GoSpursGoNL** [comment]
For me the situation is the same as my last message in: https://github.com/home-assistant/plugin-audio/issues/157#issuecomment-1850170144
So some sounds work, but f.i. TTS towards the speaker generates no sound. I suspect it has to do with the nr of hz of the audio source.

**Comment by agners** [comment]
@GoSpursGoNL what HAOS version are you on? You are using the N2+ as well correct?

I've just double checked on my end, running this service runs on HAOS 11.4 + Supervisor 2023.12.0 + Core 2024.1.2

```
service: tts.google_translate_say
data:
  cache: false
  entity_id: media_player.vlc_telnet
  message: This is a hello world
```

I am not aware in any changes in HAOS 11.4 which should affect audio. Out of curiosity I've also downgraded to 11.2, and the same service call seems to work fine here.

My `ha audio info` output:

```
# ha audio info
audio:
  application: []
  card:
  - driver: module-alsa-card.c
    index: 0
    name: alsa_card.platform-sound
    profiles:
    - active: true
      description: Analog Stereo Output
      name: output:analog-stereo
    - active: false
      description: Digital Stereo (HDMI) Output
      name: output:hdmi-stereo
    - active: false
      description: Digital Surround 5.1 (HDMI) Output
      name: output:hdmi-surround
    - active: false
      description: Digital Surround 7.1 (HDMI) Output
      name: output:hdmi-surround71
    - active: false
      description: "Off"
      name: "off"
  input: []
  output:
  - applications: []
    card: 0
    default: true
    description: Built-in Audio Analog Stereo
    index: 0
    mute: false
    name: alsa_output.platform-sound.analog-stereo
    volume: 1
host: 172.30.32.4
update_available: false
version: 2023.12.0
version_latest: 2023.12.0
```

Can you test this again and check/upload the following logs:

```
ha core logs
ha audio logs
ha supervisor logs
ha host logs --identifier kernel
```

**Comment by GoSpursGoNL** [comment]
I switched to the Odroid M1 in the meantime: https://github.com/home-assistant/plugin-audio/issues/157#issuecomment-1850170109
That service call you proposed (adjusted to use my entity id for the speaker media player) produces no sound.

If I let it get cached to a local audio file, where will it be put on my disk?
I like to check if I play that file to the speaker if it produces sound, check the bitrate, adjust and try again. I think this is the problem for me: https://github.com/home-assistant/plugin-audio/issues/157#issuecomment-1850170172

ha audio info:
```
audio:
  application: []
  card:
  - driver: module-alsa-card.c
    index: 0
    name: alsa_card.platform-hdmi-sound
    profiles:
    - active: true
      description: Stereo Output
      name: output:stereo-fallback
    - active: false
      description: "Off"
      name: "off"
  - driver: module-alsa-card.c
    index: 1
    name: alsa_card.platform-rk809-sound
    profiles:
    - active: false
      description: Stereo Input
      name: input:stereo-fallback
    - active: false
      description: Stereo Output
      name: output:stereo-fallback
    - active: true
      description: Stereo Output + Stereo Input
      name: output:stereo-fallback+input:stereo-fallback
    - active: false
      description: "Off"
      name: "off"
  input:
  - applications: []
    card: 1
    default: true
    description: Built-in Audio Stereo
    index: 2
    mute: false
    name: alsa_input.platform-rk809-sound.stereo-fallback
    volume: 1
  output:
  - applications: []
    card: 0
    default: false
    description: Built-in Audio Stereo
    index: 0
    mute: false
    name: alsa_output.platform-hdmi-sound.stereo-fallback
    volume: 1
  - applications: []
    card: 1
    default: true
    description: Built-in Audio Stereo
    index: 1
    mute: false
    name: alsa_output.platform-rk809-sound.stereo-fallback
    volume: 1
host: 172.30.32.4
update_available: false
version: 2023.12.0
version_latest: 2023.12.0
```
Attached the other files. Thanks for assisting!

[ha audio logs.txt](https://github.com/home-assistant/plugin-audio/files/13998471/ha.audio.logs.txt)
[ha core logs.txt](https://github.com/home-assistant/plugin-audio/files/13998472/ha.core.logs.txt)
[ha host logs identifier kernel.txt](https://github.com/home-assistant/plugin-audio/files/13998473/ha.host.logs.identifier.kernel.txt)
[ha supervisor logs.txt](https://github.com/home-assistant/plugin-audio/files/13998474/ha.supervisor.logs.txt)
