### ISSUE TITLE
Some sample rates do not work on ODROID-M1

### ISSUE THREAD

**Issue by agners** [home-assistant/plugin-audio#162]
I switched to the Odroid M1 in the meantime: https://github.com/home-assistant/plugin-audio/issues/157#issuecomment-1850170109
That service call you proposed (adjusted to use my entity id for the speaker media player) produces no sound.

If I let it get cached to a local audio file, where will it be put on my disk?
I like to check if I play that file to the speaker if it produces sound, check the hz, adjust and try again. I think this is the problem for me: https://github.com/home-assistant/plugin-audio/issues/157#issuecomment-1850170172

ha audio info:
```
audio:
  application: []
  card:
  - driver: module-alsa-card.c
    index: 0
    name: alsa_card.platform-hdmi-sound
    profiles:
    - active: true
      description: Stereo Output
      name: output:stereo-fallback
    - active: false
      description: "Off"
      name: "off"
  - driver: module-alsa-card.c
    index: 1
    name: alsa_card.platform-rk809-sound
    profiles:
    - active: false
      description: Stereo Input
      name: input:stereo-fallback
    - active: false
      description: Stereo Output
      name: output:stereo-fallback
    - active: true
      description: Stereo Output + Stereo Input
      name: output:stereo-fallback+input:stereo-fallback
    - active: false
      description: "Off"
      name: "off"
  input:
  - applications: []
    card: 1
    default: true
    description: Built-in Audio Stereo
    index: 2
    mute: false
    name: alsa_input.platform-rk809-sound.stereo-fallback
    volume: 1
  output:
  - applications: []
    card: 0
    default: false
    description: Built-in Audio Stereo
    index: 0
    mute: false
    name: alsa_output.platform-hdmi-sound.stereo-fallback
    volume: 1
  - applications: []
    card: 1
    default: true
    description: Built-in Audio Stereo
    index: 1
    mute: false
    name: alsa_output.platform-rk809-sound.stereo-fallback
    volume: 1
host: 172.30.32.4
update_available: false
version: 2023.12.0
version_latest: 2023.12.0
```
Attached the other files. Thanks for assisting!

[ha audio logs.txt](https://github.com/home-assistant/plugin-audio/files/13998471/ha.audio.logs.txt)
[ha core logs.txt](https://github.com/home-assistant/plugin-audio/files/13998472/ha.core.logs.txt)
[ha host logs identifier kernel.txt](https://github.com/home-assistant/plugin-audio/files/13998473/ha.host.logs.identifier.kernel.txt)
[ha supervisor logs.txt](https://github.com/home-assistant/plugin-audio/files/13998474/ha.supervisor.logs.txt)

_Originally posted by @GoSpursGoNL in https://github.com/home-assistant/plugin-audio/issues/157#issuecomment-1902163037_
