### ISSUE TITLE
No sound devices anymore withe ha audio 2025.02.0

### ISSUE THREAD

**Issue by klodeckl** [home-assistant/plugin-audio#188]
On my raspberry PI 4B with Home Assistant OS installation sound worked perfectly, but after an update no devices were shown:

```
# ha audio info
audio:
  application: []
  card: []
  input: []
  output:
  - applications: []
    card: null
    default: true
    description: Dummy Output
    index: 5
    mute: false
    name: auto_null
    volume: 1
host: 172.30.32.4
update_available: true
version: 2025.02.0
version_latest: 2025.02.0
```

After downgrading with 

`ha audio update --version 2023.12.0`

and reloading

`ha audio reload`

sound devices are listed again:

```
# ha audio info
audio:
  application: []
  card:
  - driver: module-alsa-card.c
    index: 0
    name: alsa_card.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00
    profiles:
    - active: false
      description: Analog Stereo Input
      name: input:analog-stereo
    - active: false
      description: Digital Stereo (IEC958) Input
      name: input:iec958-stereo
    - active: false
      description: Analog Stereo Output
      name: output:analog-stereo
    - active: true
      description: Analog Stereo Duplex
      name: output:analog-stereo+input:analog-stereo
    - active: false
      description: Analog Stereo Output + Digital Stereo (IEC958) Input
      name: output:analog-stereo+input:iec958-stereo
    - active: false
      description: Digital Stereo (IEC958) Output
      name: output:iec958-stereo
    - active: false
      description: Digital Stereo (IEC958) Output + Analog Stereo Input
      name: output:iec958-stereo+input:analog-stereo
    - active: false
      description: Digital Stereo Duplex (IEC958)
      name: output:iec958-stereo+input:iec958-stereo
    - active: false
      description: "Off"
      name: "off"
  - driver: module-alsa-card.c
    index: 1
    name: alsa_card.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.2
    profiles:
    - active: false
      description: Analog Stereo Input
      name: input:analog-stereo
    - active: false
      description: Digital Stereo (IEC958) Input
      name: input:iec958-stereo
    - active: false
      description: Analog Stereo Output
      name: output:analog-stereo
    - active: true
      description: Analog Stereo Duplex
      name: output:analog-stereo+input:analog-stereo
    - active: false
      description: Analog Stereo Output + Digital Stereo (IEC958) Input
      name: output:analog-stereo+input:iec958-stereo
    - active: false
      description: Digital Stereo (IEC958) Output
      name: output:iec958-stereo
    - active: false
      description: Digital Stereo (IEC958) Output + Analog Stereo Input
      name: output:iec958-stereo+input:analog-stereo
    - active: false
      description: Digital Stereo Duplex (IEC958)
      name: output:iec958-stereo+input:iec958-stereo
    - active: false
      description: "Off"
      name: "off"
  - driver: module-alsa-card.c
    index: 2
    name: alsa_card.usb-CMEDIA_BC_USB_DAC-00
    profiles:
    - active: true
      description: Analog Stereo Output
      name: output:analog-stereo
    - active: false
      description: Digital Stereo (IEC958) Output
      name: output:iec958-stereo
    - active: false
      description: "Off"
      name: "off"
  - driver: module-alsa-card.c
    index: 3
    name: alsa_card.platform-bcm2835_audio
    profiles:
    - active: true
      description: Stereo Output
      name: output:stereo-fallback
    - active: false
      description: "Off"
      name: "off"
  - driver: module-alsa-card.c
    index: 4
    name: alsa_card.platform-soc_sound
    profiles:
    - active: true
      description: Stereo Output
      name: output:stereo-fallback
    - active: false
      description: "Off"
      name: "off"
  input:
  - applications: []
    card: 0
    default: false
    description: USB Audio CODEC  Analog Stereo
    index: 1
    mute: false
    name: alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo
    volume: 1
  - applications: []
    card: 1
    default: true
    description: USB Audio CODEC  Analog Stereo
    index: 3
    mute: false
    name: alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo.2
    volume: 1
  output:
  - applications: []
    card: 0
    default: false
    description: USB Audio CODEC  Analog Stereo
    index: 0
    mute: false
    name: alsa_output.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo
    volume: 1
  - applications: []
    card: 1
    default: false
    description: USB Audio CODEC  Analog Stereo
    index: 1
    mute: false
    name: alsa_output.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo.2
    volume: 1
  - applications: []
    card: 2
    default: false
    description: BC USB DAC Analog Stereo
    index: 2
    mute: false
    name: alsa_output.usb-CMEDIA_BC_USB_DAC-00.analog-stereo
    volume: 1
  - applications: []
    card: 3
    default: false
    description: Built-in Audio Stereo
    index: 3
    mute: false
    name: alsa_output.platform-bcm2835_audio.stereo-fallback
    volume: 0.857696533203125
  - applications: []
    card: 4
    default: true
    description: Built-in Audio Stereo
    index: 4
    mute: false
    name: alsa_output.platform-soc_sound.stereo-fallback
    volume: 1
host: 172.30.32.4
update_available: true
version: 2023.12.0
version_latest: 2025.02.0
```

(I have three USB soundcards and a Justboom Amp HAT connected)

Core: 2025.6.0
Supervisor: 2025.05.5
Operating System: 15.2
Frontend: 20250531.2
