### ISSUE TITLE
Access `pactl` from HA core

### ISSUE THREAD

**Issue by y0ast** [home-assistant/plugin-audio#21]
Hi HA team!

The new audio changes work well, using the web terminal addon I can successfully change the volume on my pi (output is through a DAC hat): `pactl set-sink-volume 0 80%` and `ha audio info` works as expected.

However inside a [shell_command](https://www.home-assistant.io/integrations/shell_command/), I seem to have no access to `pactl` or `amixer`. Consistently giving me `not found` errors.

Is this expected? Is there an alternative way to call `pactl` from inside core?

**Comment by pvizeli** [comment]
We can expose the Supervisor audio API to Core and make service calls from that like we have for other function on Supervisor.

**Comment by y0ast** [comment]
Oh that would be amazing. With the updated Spotify addon and that feature, HA would become an excellent media player.

**Comment by y0ast** [comment]
I got it working :)

in a shell script `/config/volume.sh`:
```
curl -X POST -H "Authorization: Bearer ${SUPERVISOR_TOKEN}" \
             -H "Content-Type: application/json" \
             -d '{"index": 0, "volume": '$1'}' \
                http://supervisor/audio/volume/output
```

```
input_number:
  pi_volume:
    icon: mdi:volume-high
    name: Volume
    initial: 0.5
    min: 0.0
    max: 1.0
    step: 0.1

shell_command:
    set_internal_speaker_volume: /config/volume.sh '{{ states.input_number.pi_volume.state | float}}'

automation:
  - id: 'pi_volume'
    alias: Pi Volume
    trigger:
      - entity_id: input_number.pi_volume
        platform: state
    action:
      - service: shell_command.set_internal_speaker_volume
```

Thanks @pvizeli for adding the docs back to the api!
